#!/usr/bin/env python

"""Usage:
free_wilson.py all --scaffold SCAFFOLD_MOLFILE --in INPUT_SMILES_FILE --prefix JOB_PREFIX --act ACTIVITY_FILE [--log]
free_wilson.py rgroup --scaffold SCAFFOLD_MOLFILE --in INPUT_SMILES_FILE --prefix JOB_PREFIX
free_wilson.py regression --desc DESCRIPTOR_FILE --act ACTIVITY_FILE --prefix JOB_PREFIX [--log]
free_wilson.py enumeration --scaffold SCAFFOLD_MOLFILE --model MODEL_FILE --desc DESCRIPTOR_FILE --prefix JOB_PREFIX

Options:
--scaffold SCAFFOLD_MOLFILE molfile with labeled R-groups
--in INPUT_SMILES_FILE input SMILES file
--prefix JOB_PREFIX job prefix
--desc DESCRIPTOR_FILE as generated by the "rgroup" command
--act ACTIVITY_FILE activity column should be labeled "Act" in the header
--model MODEL_FILE names of the model file created by the "regression" command
"""

from docopt import docopt

from free_wilson_enumeration import free_wilson_enumeration
from free_wilson_regression import free_wilson_regression
from free_wilson_rgroup import free_wilson_rgroup

cmd_input = docopt(__doc__)

if cmd_input.get("all"):
    core_file_name = cmd_input.get("--scaffold")
    input_smiles = cmd_input.get("--in")
    prefix = cmd_input.get("--prefix")
    do_log = cmd_input.get("--log")
    activity_file_name = cmd_input.get("--act")
    descriptor_file_name = prefix+"_vector.csv"
    model_file_name = prefix+"_lm.pkl"
    free_wilson_rgroup(core_file_name, input_smiles, prefix)
    free_wilson_regression(descriptor_file_name, activity_file_name, prefix, do_log)
    free_wilson_enumeration(core_file_name, model_file_name,descriptor_file_name,prefix)

elif cmd_input.get("rgroup"):
    core_file_name = cmd_input.get("--scaffold")
    input_smiles = cmd_input.get("--in")
    prefix = cmd_input.get("--prefix")
    free_wilson_rgroup(core_file_name, input_smiles, prefix)

elif cmd_input.get("regression"):
    descriptor_file_name = cmd_input.get("--desc")
    activity_file_name = cmd_input.get("--act")
    prefix = cmd_input.get("--prefix")
    do_log = cmd_input.get("--log")
    free_wilson_regression(descriptor_file_name, activity_file_name, prefix, do_log)

elif cmd_input.get("enumeration"):
    core_file_name = cmd_input.get("--scaffold")
    model_file_name = cmd_input.get("--model")
    descriptor_file_name = cmd_input.get("--desc")
    prefix = cmd_input.get("--prefix")
    free_wilson_enumeration(core_file_name, model_file_name,descriptor_file_name,prefix)


